# Neo4j Configurations
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: capstone
  clean_database: clean2
  processed_database: processed2

# Bitcoin RPC API
rpc:
  ip: 192.168.141.148
  port: 5001
  username: duck
  password: duck2

# Clustering Analysis
dbscan:
  eps: 0.6
  min_points: 8
  time_window: 15
